# Generated by Django 5.0.6 on 2024-05-13 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_previous_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created']},
        ),
        migrations.RemoveField(
            model_name='message',
            name='previous_message',
        ),
    ]
